{"name": "test2", "status": "failed", "statusDetails": {"message": "AssertionError: True != \"It's not a Match.\"", "trace": "self = <test_test.test_case2 testMethod=test2>\n\n    @allure.feature('Open')\n    def test2(self):\n        s1 =\"Ruby\"\n        s2 =\"Ruby\"\n        # Verifying Numbers\n>       self.assertEquals(s1 == s2, \"It's not a Match.\")\nE       AssertionError: True != \"It's not a Match.\"\n\ntest_test.py:48: AssertionError"}, "start": 1698339937403, "stop": 1698339937403, "uuid": "72d393cc-edab-4a72-be5b-0ed338107141", "historyId": "96052ee4f98eac2c25c050040c5cfe7e", "testCaseId": "96052ee4f98eac2c25c050040c5cfe7e", "fullName": "test_test.test_case2#test2", "labels": [{"name": "feature", "value": "Open"}, {"name": "suite", "value": "test_test"}, {"name": "subSuite", "value": "test_case2"}, {"name": "host", "value": "vpotapov"}, {"name": "thread", "value": "2132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_test"}]}